API_ID: 13532780
API_HASH: f73ffaec3acf05270cde1dc63c561ef0
BOT_TOKEN: 5488093071:AAG8VZllZCBr3Xfu1nrFejqeUMbHI0bU63A


MONGO_URL: mongodb+srv://Bot:C0m0erl.@bot.6hlmv7x.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-16488.c60.us-west-1-2.ec2.cloud.redislabs.com
REDIS_PORT: 16488
REDIS_PASS: wipwKeqbNM0rnBV4hHk791Vq6xhdUdv6

SESSION_API_ID: 13532780
SESSION_API_HASH: f73ffaec3acf05270cde1dc63c561ef0
SESSION_STRING: 1AZWarzUBu1yeNStTzzl-odMQL87FdGLape4D3fkY3ZWfHtsDSctwjQJ29pnCxtKIohdMIsK93L9G9Azp44HErJApRch5ry9FGJkCUKytt3Z1ftsIls5BI06UmO4TKKSQD3QbGuJ2KHlX-0HVDhM1JPC4Y4GMKzTI8QyMVmlf0oY81zDzKrBilmI92j7C5f54yEv0uibnBKVfDsYFer1hoqkfMvv7U3oKT2yNNA3VghDyCHSDfNGVcbhe0D923UcYQdPSBJxhJ1MFKOCMiShWL__WXCknIPxUqK5UJADKB1U9N5NK07HEXuqVRO1eajd-6ZjXPtx5bzoDKvL-FUYY-Bl3zVASbuk=

ADMINS: 
  - 1924666696

OWNER: 1924666696

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: MarGroupVip 
# LOG_CHAT: 
LOG_CHAT: -1001698417714



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

